wget -c http://www.podcastsinenglish.com/listen/level1/toys.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/city.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/deliveries.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/portugal.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/yoga.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/memory.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/flowers.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/chinese1.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/chinese2.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/2014questions.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/2014quiz.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/thanksgiving.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/fall.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/holiday.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/bad_habits.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/swimming.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/brazil.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/may.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/eastereggs.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/diary.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/art.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/xmas_poems.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/xmas_meals.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/bonfire.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/school.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/prince.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/rubbish.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/tea.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/hotel3.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/hotel2.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/oddanimals.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/winter.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/world.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/felix.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/art.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/rio.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/beachhut.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/fingers.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/icecream.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/torch.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/teacher.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/lost.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/laura.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/soap.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/occupy.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/chocolates.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/ana.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/house2.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/penela.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/study.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/spring.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/royals.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/amazon.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/chores.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/presents2.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/senses.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/chickens.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/quiz.mp3
wget -c http://www.podcastsinenglish.com/listen/level1/country.mp3
