wget -c http://www.podcastsinenglish.com/listen/levelb/nostalgia.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/vw.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/crowdfunding2.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/amalgamation.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/choice.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/export.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/crowdfunding1.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/import.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/blackfriday.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/mood.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/bargain.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/bitcoins.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/customer_service.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/taxi.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/fifa.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/cooker.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/sugru.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/cafe.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/booking2.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/boycott.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/twitter.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/socialmedia.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/booking1.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/summit.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/webdesign.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/office2.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/office1.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/horsemeat2.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/highstreet.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/corporation_tax.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/commute.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/poundland.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/sunday.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/shard.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/marketsociety.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/accountant.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/sponsor.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/startup2.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/startup.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/marketing.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/advert.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/service.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/wales.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/greece.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/small_business.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/osama.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/negotiating.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/eu.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/google.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/google_extra.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/corp.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/code.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/newsbulletin1.mp3
wget -c http://www.podcastsinenglish.com/listen/levelb/boss.mp3
