wget -c http://www.podcastsinenglish.com/listen/level2/2015qq.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/2015qa.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/calendars.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/cowboy.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/flag.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/bluemoon.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/jaws.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/brain.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/soda.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/dieting.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/boardgames.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/realmadrid.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/gadgets.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/comics.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/driving.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/ww1.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/world_cup.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/easter.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/tramp.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/mouse.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/horse.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/drwho.mp3
wget -c http://www.podcastsinenglish.com/wksheets/level2/drwho_sounds.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/mushrooms.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/catchingup.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/whales.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/grandprix.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/everest.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/cheese.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/pope.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/cold.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/numbers.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/christmas_tree.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/guidedogs.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/oldage.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/postgrad.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/paralympics.mp3
wget -c http://www.podcastsinenglish.com/wksheets/level2/paralympics_extra.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/beatles.mp3
wget -c http://www.podcastsinenglish.com/wksheets/level2/beatles_extra.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/skydiver.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/lottery2.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/lottery1.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/comforts.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/year2011.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/antarctic.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/poppy.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/bake.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/camping.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/tennis_serve.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/twist.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/planking.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/wedding.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/bees.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/islands.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/2011.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/rain.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/kids.mp3
wget -c http://www.podcastsinenglish.com/wksheets/level2/kids_extra.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/camera.mp3
wget -c http://www.podcastsinenglish.com/listen/level2/volunteer.mp3
