wget -c http://www.podcastsinenglish.com/listen/level3/bond.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/funerals.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/refugees.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/voting.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/cricket.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/heist.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/comment.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/sun.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/sun.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/diet.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/windy.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/knitting.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/blue.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/cars.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/picnic.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/umpires.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/999.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/internet2.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/sinkholes.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/rockclimbing.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/sochi.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/2013review1.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/2013review2.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/poetry.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/poetry_poem.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/citizenship.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/pickpockets.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/tour.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/george.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/umami.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/jury.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/carnival.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/tube.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/coffee.mp3
wget -c http://www.podcastsinenglish.com/wksheets/level3/coffee_extra.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/cycling.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/harvest.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/moon.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/london_olympics.mp3
wget -c http://www.podcastsinenglish.com/wksheets/level3/london_olympics_extra.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/vision.mp3
wget -c http://www.podcastsinenglish.com/wksheets/level3/vision_extra.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/baku.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/marathon.mp3
wget -c http://www.podcastsinenglish.com/wksheets/level3/marathon_extra.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/women.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/bench.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/panto.mp3
wget -c http://www.podcastsinenglish.com/wksheets/level3/panto_extra.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/movember.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/fire.mp3
wget -c http://www.podcastsinenglish.com/wksheets/level3/fire_extra.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/mac.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/hendrik.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/ironman.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/festival.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/india.mp3
wget -c http://www.podcastsinenglish.com/whsheets/level3/india_extra.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/beez.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/nose.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/names2.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/name.mp3
wget -c http://www.podcastsinenglish.com/wksheets/level3/name.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/happiness.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/mine.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/brands.mp3
wget -c http://www.podcastsinenglish.com/wksheets/level3/brands_extra.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/cry.mp3
wget -c http://www.podcastsinenglish.com/listen/level3/diy.mp3
